### ISSUE TITLE
Junior - Model assets from 3D asset list (3h)

### ISSUE THREAD

**Issue by Yuioppoiuy** [UoSGamesGroups/level-6-l6-group-9#3]

**Comment by Junior1441** [comment]
Done the modelling. Took me an hour to finish it.

**Comment by Junior1441** [comment]
Spent 3 hours making 3 model

**Comment by Junior1441** [comment]
Spent 3 hours making 4 model

**Comment by Junior1441** [comment]
Spend an hour modelling a sink. Have 2 hour remaining to do some other assets.

**Comment by Junior1441** [comment]
spent 2 hours working on models and improving some models
